### Create a new Customer
POST http://localhost:1234/api/customers
Accept: application/json
Content-Type: application/json

{
    "email": "haritha@gmail.com",
    "name" : "Haritha Kumari",
    "password": "secret123"
}